spring.application.name=dividaAPI
spring.application.url=jdbc:postgresql://localhost:5433/divida
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

