# Conexão com o banco local
spring.application.name=dividaAPI
spring.datasource.url=jdbc:postgresql://localhost:5432/divida_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Segurança - credenciais do cliente
security.client-id=divida-api
security.client-secret=divida-api-secret
security.username=admin
security.password=admin123

security.jwt.secret=divida-api-secret-key-2026-very-long-secret
spring.security.session.creation-policy=STATELESS